Removing extra spaces in program + note
Just like the other files, this one wasn't made in the terminal I use. Many errors need to get resolved - Ubuntu Windows 11
error: failed to push some refs to 'https://github.com/ijeanty/1115.git'
Help is needed